// Copyright (c) 2026, Oliver Kohlbacher and the ODIA authors.
// SPDX-License-Identifier: BSD-3-Clause
//
// GENERATED by scripts/generate_peptdeep_elements.py -- do not edit.

#pragma once

#include <array>
#include <cstddef>
#include <optional>
#include <string_view>

namespace ODIA
{

  /// AlphaPeptDeep's mod_elements. The index is the feature position.
  inline constexpr std::array<std::string_view, 109>
    PEPTDEEP_MOD_ELEMENTS{
      "C", "H", "N", "O", "P", "S", "B", "F",
      "I", "K", "U", "V", "W", "X", "Y", "Ac",
      "Ag", "Al", "Am", "Ar", "As", "At", "Au", "Ba",
      "Be", "Bi", "Bk", "Br", "Ca", "Cd", "Ce", "Cf",
      "Cl", "Cm", "Co", "Cr", "Cs", "Cu", "Dy", "Er",
      "Es", "Eu", "Fe", "Fm", "Fr", "Ga", "Gd", "Ge",
      "He", "Hf", "Hg", "Ho", "In", "Ir", "Kr", "La",
      "Li", "Lr", "Lu", "Md", "Mg", "Mn", "Mo", "Na",
      "Nb", "Nd", "Ne", "Ni", "No", "Np", "Os", "Pa",
      "Pb", "Pd", "Pm", "Po", "Pr", "Pt", "Pu", "Ra",
      "Rb", "Re", "Rh", "Rn", "Ru", "Sb", "Sc", "Se",
      "Si", "Sm", "Sn", "Sr", "Ta", "Tb", "Tc", "Te",
      "Th", "Ti", "Tl", "Tm", "Xe", "Yb", "Zn", "Zr",
      "2H", "13C", "15N", "18O", "?",
    };

  /// Index of an element, or nullopt if the symbol is not in the list.
  ///
  /// The found/not-found bit is part of the contract, not a convenience:
  /// upstream ASSIGNS a known element's count and ACCUMULATES an unknown
  /// one into the '?' slot, so a caller that cannot tell them apart gets
  /// one of the two cases wrong. Returning the '?' index for both made
  /// two unknown symbols in one formula collapse to the last.
  inline constexpr std::optional<std::size_t>
  peptDeepElementIndex(std::string_view symbol)
  {
    for (std::size_t i = 0; i < PEPTDEEP_MOD_ELEMENTS.size(); ++i)
    {
      if (PEPTDEEP_MOD_ELEMENTS[i] == symbol) { return i; }
    }
    return std::nullopt;
  }

  /// The '?' catch-all slot, where unknown elements accumulate.
  inline constexpr std::size_t PEPTDEEP_UNKNOWN_ELEMENT =
    PEPTDEEP_MOD_ELEMENTS.size() - 1;

} // namespace ODIA
