#!/usr/bin/env python
"""Regenerate the PeptDeep element list from AlphaPeptDeep's model_const.yaml.

The list is not hand-maintained: the index IS the feature position in the
109-wide mod_x tensor, and a hand-typed copy came out with 112 entries.

  generate_peptdeep_elements.py <model_const.yaml>

Rewrites data/peptdeep_mod_elements.txt and include/odia/PeptDeepElements.h.
Note that the yaml quotes 'No' deliberately -- YAML 1.1 reads a bare No as
false -- so the text file must never be round-tripped through a YAML loader.
"""
import os
import sys

root = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")


def extract(path):
    out, inside = [], False
    for line in open(path):
        s = line.strip()
        if s.startswith("#") or not s:
            continue
        if s.startswith("mod_elements:"):
            inside = True
            continue
        if inside:
            if s.startswith("- "):
                out.append(s[2:].strip().strip("\"'"))
            else:
                break
    if len(out) != 109:
        raise SystemExit(f"expected 109 elements, got {len(out)}")
    if len(set(out)) != len(out):
        raise SystemExit("duplicate element symbols would make lookup ambiguous")
    return out


def main(yaml_path):
    els = extract(yaml_path)
    with open(f"{root}/data/peptdeep_mod_elements.txt", "w") as fh:
        fh.write("# AlphaPeptDeep's mod_elements, in order. The index IS the feature\n")
        fh.write("# position in the 109-wide mod_x tensor, so the order is load-bearing.\n#\n")
        fh.write("# Source: MannLabs/alphapeptdeep, peptdeep/constants/model_const.yaml,\n")
        fh.write("# key `mod_elements`. Extracted by scripts/generate_peptdeep_elements.py,\n")
        fh.write("# never hand-typed: a hand-typed copy had 112 entries and diverged at 38.\n")
        fh.write("# Corroborated independently by the shipped models, whose mod_x input is\n")
        fh.write("# declared [batch, seq_length, 109].\n")
        fh.write("\n".join(els) + "\n")

    with open(f"{root}/include/odia/PeptDeepElements.h", "w") as fh:
        fh.write("// Copyright (c) 2026, Oliver Kohlbacher and the ODIA authors.\n")
        fh.write("// SPDX-License-Identifier: BSD-3-Clause\n//\n")
        fh.write("// GENERATED by scripts/generate_peptdeep_elements.py -- do not edit.\n\n")
        fh.write("#pragma once\n\n#include <array>\n#include <cstddef>\n")
        fh.write("#include <optional>\n#include <string_view>\n\n")
        fh.write("namespace ODIA\n{\n\n")
        fh.write("  /// AlphaPeptDeep's mod_elements. The index is the feature position.\n")
        fh.write(f"  inline constexpr std::array<std::string_view, {len(els)}>\n")
        fh.write("    PEPTDEEP_MOD_ELEMENTS{\n")
        for i in range(0, len(els), 8):
            fh.write("      " + ", ".join(f'"{e}"' for e in els[i:i + 8]) + ",\n")
        fh.write("    };\n\n")
        fh.write("  /// Index of an element, or nullopt if the symbol is not in the list.\n")
        fh.write("  ///\n")
        fh.write("  /// The found/not-found bit is part of the contract, not a convenience:\n")
        fh.write("  /// upstream ASSIGNS a known element's count and ACCUMULATES an unknown\n")
        fh.write("  /// one into the '?' slot, so a caller that cannot tell them apart gets\n")
        fh.write("  /// one of the two cases wrong. Returning the '?' index for both made\n")
        fh.write("  /// two unknown symbols in one formula collapse to the last.\n")
        fh.write("  inline constexpr std::optional<std::size_t>\n")
        fh.write("  peptDeepElementIndex(std::string_view symbol)\n  {\n")
        fh.write("    for (std::size_t i = 0; i < PEPTDEEP_MOD_ELEMENTS.size(); ++i)\n")
        fh.write("    {\n      if (PEPTDEEP_MOD_ELEMENTS[i] == symbol) { return i; }\n    }\n")
        fh.write("    return std::nullopt;\n  }\n\n")
        fh.write("  /// The '?' catch-all slot, where unknown elements accumulate.\n")
        fh.write("  inline constexpr std::size_t PEPTDEEP_UNKNOWN_ELEMENT =\n")
        fh.write("    PEPTDEEP_MOD_ELEMENTS.size() - 1;\n\n")
        fh.write("} // namespace ODIA\n")
    print(f"regenerated {len(els)} elements")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "/scratch/kohlbach/odia/model_const.yaml")
